spring:
  application:
    name: Auth-Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB.URL:jdbc:postgresql://localhost:5432/parking_lot}
    username: ${DB.USERNAME:postgres}
    password: ${DB.PASSWORD:password}
  data:
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}

eureka:
  instance:   
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA.DEFAULT.ZONE.URL:http://localhost:8761/eureka}

server:
  port: ${AUTH.SERVICE.SERVER.PORT:8080}
  servlet:
    context-path: /

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs/auth
  cache:
    disabled: true

openapi:
  service:
    url: ${API.GATEWAY.SERVICE.URL:http://localhost:80}

token:
  key: ${token.signing.key:Hr6RvNnuoWZ1KxlEYeh2RS/WcoLJZb0e4d/r9/kqajQ=}


