spring:
  application:
    name: Notification-Service
  data:
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}
server:
  port: ${NOTIFICATION.SERVICE.SERVER.PORT:8181}


app:
  telegram:
    username: ${app.telegram.username:parking_lot_locator_bot}
    token: ${app.telegram.token:6478988761:AAHoiepwTE0Bh8JjK_2piQIjDD8wyGl-qN8}


#management:
#  tracing:
#    sampling:
#      probability: 1.0

