spring:
  application:
    name: Notification-Service



#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8181


app:
  telegram:
    username: ${app.telegram.username:parking_lot_locator_bot}
    token: ${app.telegram.token:6478988761:AAHoiepwTE0Bh8JjK_2piQIjDD8wyGl-qN8}


management:
  tracing:
    sampling:
      probability: 1.0

