spring:
  application:
    name: Notification-Service

  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}
server:
  port: ${NOTIFICATION.SERVICE.SERVER.PORT:8181}

redishost: ${REDIS.HOST:localhost}
redisport: ${REDIS.PORT:6379}
app:
  telegram:
    username: ${TELEGRAM.USERNAME:parking_lot_locator_bot}
    token: ${TELEGRAM.TOKEN:6478988761:AAHoiepwTE0Bh8JjK_2piQIjDD8wyGl-qN8}


#management:
#  tracing:
#    sampling:
#      probability: 1.0

