spring:
  application:
    name: Notification-Service
  data:
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}
server:
  port: ${NOTIFICATION.SERVICE.SERVER.PORT:8181}


app:
  telegram:
    username: ${TELEGRAM.USERNAME:parking_lot_locator_bot}
    token: ${TELEGRAM.TOKEN:token}

notification:
  service:
    url: ${NOTIFICATION.SERVER.URL:localhost:8080}
#management:
#  tracing:
#    sampling:
#      probability: 1.0

