spring:
  application:
    name: Geo-Location-Service

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081
  servlet:
    context-path: /


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


springdoc:
  api-docs:
    path: /v3/api-docs/geo-location
  cache:
    disabled: true