spring:
  application:
    name: Geo-Location-Service
management:
  tracing:
    sampling:
      probability: 1.0

redishost: ${REDIS.HOST:localhost}
redisport: ${REDIS.PORT:6379}
server:
  port: ${GEO.LOCATION.SERVICE.SERVER.PORT:8081}
  servlet:
    context-path: /
  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}

eureka:
  instance:   
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA.DEFAULT.ZONE.URL:http://localhost:8761/eureka}

openapi:
  service:
    url: ${API.GATEWAY.SERVICE.URL:http://localhost:80}

springdoc:
  api-docs:
    path: /v3/api-docs/geo-location
  cache:
    disabled: true


