spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: Auth-Service
          uri: ${AUTH.SERVICE.URL:lb://Auth-Service}
          predicates:
            - Path=/api/v1/auth/**, /v3/api-docs/auth

        - id: Geo-Location-Service
          uri: ${GEO.LOCATION.SERVICE.URL:lb://Geo-Location-Service}
          predicates:
            - Path=/api/v1/geo-location/**, /v3/api-docs/geo-location
          filters:
            - AuthenticationFilter

        - id: Parking-Lot-Service
          uri: ${PARKING.LOT.SERVICE.URL:lb://Parking-Lot-Service}
          predicates:
            - Path=/api/v1/parking-lot/**, /v3/api-docs/parking-lot
          filters:
            - AuthenticationFilter

        - id: Payment-Service
          uri: ${PAYMENT.SERVICE.URL:lb://Payment-Service}
          predicates:
            - Path=/api/v1/payment/**, /v3/api-docs/payment
          filters:
            - AuthenticationFilter

        - id: Discovery-Server
          uri: ${DISCOVERY.SERVICE.URL:http://localhost:8761}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: Discovery-Server-Static
          uri: ${DISCOVERY.SERVICE.URL:http://localhost:8761}
          predicates:
            - Path=/eureka/**

        - id: Notification-Service
          uri: ${NOTIFICATION.SERVICE.URL:ws://localhost:8181}
          predicates:
            - Path=/notification-ws/**

  application:
    name: Api-Gateway

eureka:
  client:
    service-url:
      defaultZone : ${EUREKA.DEFAULT.ZONE.URL:http://localhost:8761/eureka}


server:
  port: ${API.GATEWAY.SERVER.PORT:80}
  servlet:
    context-path: /
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    urls:
      - name: parking lot service
        url: /v3/api-docs/parking-lot
      - name: auth service
        url: /v3/api-docs/auth
      - name: geo location service
        url: /v3/api-docs/geo-location
      - name: payment service
        url: /v3/api-docs/payment

  cache:
    disabled: true
  show-actuator: true



