spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:

        - id: Auth-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/api/v1/auth/**
        - id: Parking-Lot-Service
          uri: lb://Parking-Lot-Service
          predicates:
            - Path=/api/v1/parking-lot/**


  application:
    name: Api-Gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka


server:
  port: 8008