spring:
  application:
    name: Payment-Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB.URL:jdbc:postgresql://localhost:5432/parking_lot}
    username: ${DB.USERNAME:postgres}
    password: ${DB.PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}
server:
  port: ${PAYMENT.SERVICE.SERVER.PORT:8083}
  servlet:
    context-path: /

openapi:
  service:
    url: ${API.GATEWAY.SERVICE.URL:http://localhost:80}

eureka:
  instance:   
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA.DEFAULT.ZONE.URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /v3/api-docs/payment
  cache:
    disabled: true

mpesa:
  stk:
    username: ${STK.USERNAME:jgdPJACy5TPGniKsmxahZgjYsfCn9ILI2LZanmk5kukRycGd}
    password: ${STK.PASSWORD:nLIqp5u77VqO2TKshWYAOaG33sMiCkGh7g6NOcnLKFsoneFpwnwskDaOMWs4Vgc1}
    bsc: ${STK.BSC:4040}
    pass: ${STK.PASS:9bf4e3c2fa2991a5646133384263ebe6192334202bea54ffd38a7cd270045b40}
    callBack: ${STK.CALLBACK.URL:https://0287-196-189-16-208.ngrok-free.app/api/v1/payment/mpesa/stkcallback}
  b2c:
    initiator: ${B2C.INITIATOR:parking}
    securityCredential: ${B2C.SECURITY.CREDENTIAL:YS5mM4GKgFhTYbirfliSNy+XMzAYlS9+4Juth6HKPaCjYXcOCOgLVSbzV7XdtY1FRXWnqxm7FnjFbWtBigYRMVhtOj9nqC1xzniD/d/RR1Ov3amJe+JfPlSOA2qIcKBKpS4aA4b5hjZiptvFdO0lrQ80RR7gAGOrGSOHsqLpfA/+d6DVeZC2Ey60hLayZLsfsr9CXzLj8S91hcC0zGFAj7vJEy4nT5b3Z+7rYFwTBaPZYD+xddIu0S/1xl+lcmnUGB0vCuYLR5nIp55MOZe27GP0kGvIrleR6QOXMiMhw2S1MsSzjWH/H/q5JVQYAp7nl73/8mVrk4TqHhLsduy1MA==}
    sender: ${B2C.SENDER:9898}
    resultUrl: ${B2C.RESULT.URL:https://0287-196-189-16-208.ngrok-free.app/api/v1/payment/mpesa/b2cresults}
