spring:
  application:
    name: Parking-Lot-Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB.URL:jdbc:postgresql://localhost:5432/parking_lot_v2}
    username: ${DB.USERNAME:postgres}
    password: ${DB.PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        type: trace
  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}
  flyway:
    enabled: false
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /v3/api-docs/parking-lot
  cache:
    disabled: true
#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA.DEFAULT.ZONE.URL:http://localhost:8761/eureka}

server:
  port: ${PARKING.LOT.SERVICE.SERVER.PORT:8082}
  servlet:
    context-path: /


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
   health:
    show-details: always

  tracing:
    sampling:
      probability: 1.0


