spring:
  application:
    name: Parking-Lot-Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB.URL:jdbc:postgresql://localhost:5432/parking_lot_new}
    username: ${DB.USERNAME:postgres}
    password: ${DB.PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        show_sql: true
  #        format_sql: true
  #        use_sql_comments: true
  #        type: trace
  kafka:
    bootstrap-servers: ${KAFKA.URL:localhost:9092}
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /v3/api-docs/parking-lot
  cache:
    disabled: true
#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA.DEFAULT.ZONE.URL:http://localhost:8761/eureka}

server:
  port: ${PARKING.LOT.SERVICE.SERVER.PORT:8082}
  servlet:
    context-path: /


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        event-consumer-buffer-size: 100
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - et.com.gebeya.parkinglotservice.exception.InsufficientBalance
          - et.com.gebeya.parkinglotservice.exception.ClientErrorException
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
  #  timelimiter:
  #    instances:
  #      auth:
  #        timeout-duration: 3s

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 3s
        ignore-exceptions:
          - et.com.gebeya.parkinglotservice.exception.InsufficientBalance
          - et.com.gebeya.parkinglotservice.exception.ClientErrorException
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
